# Changes here will be overwritten by Copier
_commit: 5.0.2
_src_path: https://github.com/DiamondLightSource/python-copier-template.git
author_email: gilesknap@gmail.com
author_name: Giles Knap
description: simulation of robot arm motion
distribution_name: robot-arm-sim
docker: true
docker_debug: false
docs_type: sphinx
git_platform: github.com
github_org: gilesknap
package_name: robot_arm_sim
pypi: true
repo_name: robot-arm-sim
strict_typing: false
type_checker: pyright
