replicaCount: 1

image:
  repository: ghcr.io/gilesknap/robot-arm-sim
  tag: latest
  pullPolicy: Always

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: nginx
  host: claude-robots.diamond.ac.uk
  annotations: {}
  tls: true

containerPort: 8080

resources:
  requests:
    cpu: 250m
    memory: 256Mi
  limits:
    cpu: "2"
    memory: 1Gi
